sudo: required

services:
    - docker

before_install:
    - docker build -t cqltrace/test_xenial -f tests/dockerfiles/xenial/Dockerfile .
    - docker build -t cqltrace/test_bionic -f tests/dockerfiles/bionic/Dockerfile .

script:
    - docker run -it cqltrace/test_xenial ./tests/run_all_tests.sh
    - docker run -it cqltrace/test_bionic ./tests/run_all_tests.sh
